<?PHP
//version 1.19i 20120117- Raised 15.Fakelos size ,$userLevel Access check
/*
*
*ToDO:
*
*Changes:



//version 1.19i 20120117- Raised 15.Fakelos size ,$userLevel Access check
*version 1.19g 20120117- Raised 15.Fakelos size
*ver 0.19b 20120114
* - Changed 'sql|LF' => 'if( ((date_kataliktiki <  (added a STAR to expirations)
* - Added last edited by field
* Since version 0.18c -20120110
* -ADA raised to 10 , 6 raised to 75 chars
*
* -Added out_completion_media
*version 0.18a - Katalhktikh Hmeromhnia
*version 0.17g - Multi checkboxes & year protocol
*
*
*/
//$requiredUserLevel = array(2); // allow users with user access 1 or 2
$minUserLevel=2;
//$cfgProgDir = '../phpSecurePages/phpSecurePages/';
$cfgProgDir = './phpSecurePages/phpSecurePages/';
require_once($cfgProgDir . "secure.php");
require_once "main_include.php";
?><!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
		"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>ΑΝΑΖΗΤΗΣΗ ΠΡΩΤΟΚΟΛΟΥ </title>
<style type="text/css">
	hr.pme-hr		     { border: 0px solid; padding: 0px; margin: 0px; border-top-width: 1px; height: 1px; }
	table.pme-main 	     { border: #004d9c 1px solid; border-collapse: collapse; border-spacing: 0px; width: 100%; }
	table.pme-navigation { border: #004d9c 0px solid; border-collapse: collapse; border-spacing: 0px; width: 100%; }
	td.pme-navigation-0, td.pme-navigation-1 { white-space: nowrap; }
	th.pme-header	     { border: #004d9c 1px solid; padding: 4px; background: #add8e6; }
	td.pme-key-0, td.pme-value-0, td.pme-help-0, td.pme-navigation-0, td.pme-cell-0,
	td.pme-key-1, td.pme-value-1, td.pme-help-0, td.pme-navigation-1, td.pme-cell-1,
	td.pme-sortinfo, td.pme-filter { border: #004d9c 1px solid; padding: 3px; }
	td.pme-buttons { text-align: left;   }
	td.pme-message { text-align: center; }
	td.pme-stats   { text-align: right;  }
</style>
<style type="text/css">@import url("jscalendar-1.0/calendar-win2k-1.css");</style>
<script type="text/javascript" src="jscalendar-1.0/calendar.js"></script>
<script type="text/javascript" src="jscalendar-1.0/lang/calendar-en.js"></script>
<script type="text/javascript" src="jscalendar-1.0/calendar-setup_stripped.js"></script>




</head>
<body>
<h3>ΔΙΑΧΕΙΡΙΣΗ ΠΡΩΤΟΚΟΛΟΥ </h3>
<?php
//include_once "main_menu.php";
/*
 * IMPORTANT NOTE: This generated file contains only a subset of huge amount
 * of options that can be used with phpMyEdit. To get information about all
 * features offered by phpMyEdit, check official documentation. It is available
 * online and also for download on phpMyEdit project management page:
 *
 * http://platon.sk/projects/main_page.php?project_id=5
 *
 * This file was generated by:
 *
 *                    phpMyEdit version: 5.7.1
 *       phpMyEdit.class.php core class: 1.204
 *            phpMyEditSetup.php script: 1.50
 *              generating setup script: 1.50
 */

// MySQL host name, user name, password, database, and table

$opts['tb'] = 'protocol_entries';

/*//LOCAL
$opts['hn'] = 'localhost';
$opts['un'] = 'john';
$opts['pw'] = 'john';
$opts['db'] = 'pde_protocol';
$opts['tb'] = 'protocol_entries';
*/

// Name of field which is the unique key
$opts['key'] = 'id';

// Type of key field (int/real/string/date etc.)
$opts['key_type'] = 'int';

// Sorting field(s)
$opts['sort_field'] = array('id');

// Number of records to display on the screen
// Value of -1 lists all records in a table
$opts['inc'] = 100;

// Options you wish to give the users
// A - add,  C - change, P - copy, V - view, D - delete,
// F - filter, I - initial sort suppressed
//$opts['options'] = 'ACVDF';

if($userLevel>=7) {
	$opts['options'] = 'ACVF'; // All but DELETE (ADD,VIEW,FILTER,CHANGE)
} else if($userLevel>=5){
	$opts['options'] = 'AVF';  // Changed for ADD only user (ADD,VIEW,FILTER)
} else {
	$opts['options'] = 'VF';  // Changed for VIEW only user (View ,Filter)
}


$opts['cgi']['append']['PME_sys_fl'] = 1;  //always show filter
$opts['sort_field'] = array('-protocol_year','-protocol_number');  //Initail sort using protocol number DESC

// Number of lines to display on multiple selection filters
$opts['multiple'] = '4';

// Navigation style: B - buttons (default), T - text links, G - graphic links
// Buttons position: U - up, D - down (default)
$opts['navigation'] = 'UDGB';
//$opts['navigation'] = 'DB';

// Display special page elements
$opts['display'] = array(
	'form'  => true,
	'query' => true,
	'sort'  => true,
	'time'  => true,
	'tabs'  => true
);

// Set default prefixes for variables
$opts['js']['prefix']               = 'PME_js_';
$opts['dhtml']['prefix']            = 'PME_dhtml_';
$opts['cgi']['prefix']['operation'] = 'PME_op_';
$opts['cgi']['prefix']['sys']       = 'PME_sys_';
$opts['cgi']['prefix']['data']      = 'PME_data_';

/* Get the user's default language and use it if possible or you can
   specify particular one you want to use. Refer to official documentation
   for list of available languages. */
//$opts['language'] = $_SERVER['HTTP_ACCEPT_LANGUAGE'] . '-UTF8';
$opts['language'] = 'EL-UTF8';

/* Table-level filter capability. If set, it is included in the WHERE clause
   of any generated SELECT statement in SQL query. This gives you ability to
   work only with subset of data from table.

$opts['filters'] = "column1 like '%11%' AND column2<17";
$opts['filters'] = "section_id = 9";
$opts['filters'] = "PMEtable0.sessions_count > 200";
*/

/* Field definitions

Fields will be displayed left to right on the screen in the order in which they
appear in generated list. Here are some most used field options documented.

['name'] is the title used for column headings, etc.;
['maxlen'] maximum length to display add/edit/search input boxes
['trimlen'] maximum length of string content to display in row listing
['width'] is an optional display width specification for the column
          e.g.  ['width'] = '100px';
['mask'] a string that is used by sprintf() to format field output
['sort'] true or false; means the users may sort the display on this column
['strip_tags'] true or false; whether to strip tags from content
['nowrap'] true or false; whether this field should get a NOWRAP
['select'] T - text, N - numeric, D - drop-down, M - multiple selection
['options'] optional parameter to control whether a field is displayed
  L - list, F - filter, A - add, C - change, P - copy, D - delete, V - view
            Another flags are:
            R - indicates that a field is read only
            W - indicates that a field is a password field
            H - indicates that a field is to be hidden and marked as hidden
['URL'] is used to make a field 'clickable' in the display
        e.g.: 'mailto:$value', 'http://$value' or '$page?stuff';
['URLtarget']  HTML target link specification (for example: _blank)
['textarea']['rows'] and/or ['textarea']['cols']
  specifies a textarea is to be used to give multi-line input
  e.g. ['textarea']['rows'] = 5; ['textarea']['cols'] = 10
['values'] restricts user input to the specified constants,
           e.g. ['values'] = array('A','B','C') or ['values'] = range(1,99)
['values']['table'] and ['values']['column'] restricts user input
  to the values found in the specified column of another table
['values']['description'] = 'desc_column'
  The optional ['values']['description'] field allows the value(s) displayed
  to the user to be different to those in the ['values']['column'] field.
  This is useful for giving more meaning to column values. Multiple
  descriptions fields are also possible. Check documentation for this.
*/


$opts['fdd']['current_status_id'] = array(
  'name'     => 'ΚΑΤΑΣΤΑΣΗ ΔΙΑΔΙΚΑΣΙΑΣ',
  'select'   => 'M',
  'maxlen'   => 11,
  'sort'     => true
);

/*
added by jon
*/
$opts['fdd']['current_status_id']['values']['table']="protocol_status";
$opts['fdd']['current_status_id']['values']['column']="status_id";
$opts['fdd']['current_status_id']['values']['description']="status_name";
$opts['fdd']['current_status_id']['values']['orderby']="status_id"; //ORDERBY


$opts['fdd']['protocol_number'] = array(
  'name'     => '1.Αριθμός <BR>πρωτοκόλλου',
  'select'   => 'N',
  'maxlen'   => 11,
  //'options'  => 'AVCPDR', // auto increment
  //
    'URL' 	 => './find_files.php?seek=$value',
  'URLtarget' => '_blank',
  //  'default'  => getNextProtocolNumber() ,
  //'php|V'      => './jon/get_next_protocol_number.php',
  //'php|A'      => './jon/get_next_protocol_number.php',
  'sort'     => true
);
//$opts['triggers']['insert']['before'] = './jon/get_next_protocol_number.php';
//$opts['fdd']['protocol_number']['default'] = 23;

$opts['fdd']['protocol_year'] = array(
  'name'     => 'Έτος Πρωτ.',
  'select'   => 'D',
  //'select'   => 'N',
  'maxlen'   => 4,
  //'options'  => 'AVCPDR', // auto increment
  'default'  => getCurrentYear() ,
  //'php|V'      => './jon/get_next_protocol_number.php',
  //'php|A'      => './jon/get_next_protocol_number.php',
  'sort'     => true
);
$opts['fdd']['protocol_year']['values2']=getYearValues2();



$opts['fdd']['date_eiserx_received'] = array(
  'name'     => '2. Ημερ. <br>παραλαβής',
  'select'   => 'N',
  'maxlen'   => 10,
  'calendar' => $calendarArray,
  'sort'     => true
);
$opts['fdd']['eiserx_eggrafo_arithmos'] = array(
  'name'     => '3. Αρ. εισερχ. <br>εγγράφου',
  'select'   => 'T',
  'maxlen'   => 20,
  'sort'     => true
);
$opts['fdd']['date_of_creation_eiserx_eggrafou'] = array(
  'name'     => '4. Χρονολ. <br>εισ. <br>εγγράφου',
  'select'   => 'N',
  'maxlen'   => 10,
  'calendar' => $calendarArray,
  'sort'     => true
);
$opts['fdd']['eiserx_topos_ekdoshs'] = array(
  'name'     => '5.Τόπος <br>έκδοσης εισ.',
  'select'   => 'T',
  'maxlen'   => 20,
  'sort'     => true
);

$opts['fdd']['eiserx_arxh_ekdoshs'] = array(
  'name'     => '6.Αρχή έκδοσης',
  'select'   => 'T',
  'maxlen'   => 75,
  'sort'     => true
);
//$opts['fdd']['eiserx_arxh_ekdoshs']['textarea']['rows'] = 2;
//$opts['fdd']['eiserx_arxh_ekdoshs']['textarea']['cols'] = 25;

$opts['fdd']['eiserx_eggrafo_summary'] = array(
  'name'     => '7.Περίληψη Εισ. Εγγράφου',
  'select'   => 'T',
  'maxlen'   => 300,
  'sort'     => true
);
$opts['fdd']['eiserx_eggrafo_summary']['textarea']['rows'] = 6;
$opts['fdd']['eiserx_eggrafo_summary']['textarea']['cols'] = 50;

// ΚΑΤΑΛΗΚΤΙΚΗ ΗΜΕΡΟΜΗΝΙΑ 3 μερες ΠΡΙΝ ΑΛΛΑΞΕ ΧΡΩΜΑ
$opts['fdd']['date_kataliktiki'] = array(
  'name'     => 'Ημερ. <br>Καταληκτική',
  'select'   => 'N',
  'maxlen'   => 10,
  'calendar' => $calendarArray,
  //%Y-%m-%d  date("Ymd")
 //'sql|LF' => 'if( ((date_kataliktiki < DATE_ADD("'.(date("Y-m-d")) .'", INTERVAL 5 DAY)) AND (date_kataliktiki > "'.date("Y-m-d").'")) , CONCAT("<font color=red \">**", date_kataliktiki, "**</font>"), date_kataliktiki )' , //ok working
 'sql|LF' => 'if( ((date_kataliktiki < DATE_ADD("'.(date("Y-m-d")) .'", INTERVAL 5 DAY)) AND (date_kataliktiki > "'.date("Y-m-d").'")) , CONCAT("<font color=red \">**", date_kataliktiki, "**</font>"), date_kataliktiki )' , //ver 1.19b

  'escape' => false,
  'sort'     => true
);


/* // Removed 8 - Not used
$opts['fdd']['eiserx_ekdothhke_gia'] = array(
  'name'     => '8.Εκδόθηκε για<br> (Γραφείο,πρόσωπο,...)',
  'select'   => 'T',
  'maxlen'   => 30,
  'sort'     => true
);
*/
$opts['fdd']['out_arxh_pou_apeythynetai'] = array(
  'name'     => '9.Αρχή που <br>απευθύνεται',
  'select'   => 'T',
  'maxlen'   => 150,
  'sort'     => true
);
$opts['fdd']['out_arxh_pou_apeythynetai']['textarea']['rows'] = 3;
$opts['fdd']['out_arxh_pou_apeythynetai']['textarea']['cols'] = 50;

$opts['fdd']['out_eggrafo_summary'] = array(
  'name'     => '10.Περιληψη εξερχ. εγγρ.',
  'select'   => 'T',
  'maxlen'   => 300,
  'sort'     => true
);
$opts['fdd']['out_eggrafo_summary']['textarea']['rows'] = 6;
$opts['fdd']['out_eggrafo_summary']['textarea']['cols'] = 50;

$opts['fdd']['date_of_outgoing_doc'] = array(
  'name'     => '11.Ημερ. <br>εξερχ.<br> εγγράφου',
  'select'   => 'N',
  'maxlen'   => 10,
  'calendar' => $calendarArray,
  'sort'     => true
);

$opts['fdd']['assigned_to'] = array(
  'name'     => 'ΧΡΕΩΜΕΝΟ ΣΕ (ΓΙΑ ΕΝΕΡΓΕΙΕΣ)',
  'select'   => 'T',
  //'select|CA'   => 'M', // Multiple Selection only under EDIT (C) and Add (A)
  'select|CA'   => 'C', // Multiple Selection only under EDIT (C) and Add (A)  
  'maxlen'   => 100,
  //'nowrap'   => false,
  'sort'     => true
);
$opts['fdd']['assigned_to']['textarea']['rows'] = 4;
$opts['fdd']['assigned_to']['textarea']['cols'] = 25;

//added by jon
$table_column_name="assigned_to";
include "jon/jon_query_values2_multiselect.php";


$opts['fdd']['out_completion_media'] = array(
  'name'     => 'ΜΕΣΟ ΔΙΕΚΠΑΙΡ.',
  'select'   => 'T',
  //'select|CA'   => 'M', // Multiple Selection only under EDIT (C) and Add (A)
  'select|CA'   => 'C', // Multiple Selection only under EDIT (C) and Add (A)  
  'maxlen'   => 50,
  //'nowrap'   => false,
  'sort'     => true
);
$opts['fdd']['out_completion_media']['textarea']['rows'] = 4;
$opts['fdd']['out_completion_media']['textarea']['cols'] = 25;

//added by jon
$table_column_name="out_completion_media";
include "jon/jon_query_media_values2_multiselect.php";



$opts['fdd']['date_out_completion_date'] = array(
  'name'     => '12.Ημερ. <br>διεκπαιρέωσης',
  'select'   => 'N',
  'maxlen'   => 10,
  'calendar' => $calendarArray,
  'sort'     => true
);
/*  //remove from DB also - Not Used
$opts['fdd']['out_completion_number'] = array(
  'name'     => '13.Αρ. <br>διεκπαιρέωσης',
  'select'   => 'T',
  'maxlen'   => 20,
  'sort'     => true
);
*/
//['URL'] is used to make a field 'clickable' in the display
//        e.g.: 'mailto:$value', 'http://$value' or '$page?stuff';
$opts['fdd']['out_ada_code'] = array(
  'name'     => 'ΑΔΑ Εξ.',
  'select'   => 'T',
  'maxlen'   => 20,
  'URL' 	 => $ada_url.'$value',
  'URLtarget' => '_blank',
  'sort'     => true
);

$opts['fdd']['out_sxetikoi_arithmoi'] = array(
  'name'     => '14. Σχετικοί αρ.',
  'select'   => 'T',
  'maxlen'   => 50,
  'sort'     => true
);
$opts['fdd']['fakelos_arxeiou'] = array(
  'name'     => '15. Φάκελος <br>αρχείου',
  'select'   => 'T',
  'maxlen'   => 20,
  'sort'     => true
);
$opts['fdd']['comments'] = array(
  'name'     => '16.Παρατηρήσεις',
  'select'   => 'T',
  'maxlen'   => 150,
  'sort'     => true
);
$opts['fdd']['comments']['textarea']['rows'] = 3;
$opts['fdd']['comments']['textarea']['cols'] = 50;

/*
$opts['fdd']['assigned_to_primary'] = array(
  'name'     => 'ΚΥΡΙΑ ΧΡΕΩΣΗ',
  'select'   => 'T',
  'maxlen'   => 30,
  'sort'     => true
);

$opts['fdd']['assigned_to_primary']['values']['table']="protocol_assign_names";
$opts['fdd']['assigned_to_primary']['values']['column']="name";
$opts['fdd']['assigned_to_primary']['values']['description']="name";
$opts['fdd']['assigned_to_primary']['values']['filters']="is_active=1";  //WHERE
$opts['fdd']['assigned_to_primary']['values']['orderby']="name";  //sort
*/

$opts['fdd']['assign_to_notify_only'] = array(
  'name'     => 'ΧΡΕΩΜΕΝΟ ΣΕ <br>(ΕΝΗΜΕΡΩΣΗ ΜΟΝΟ)',
  'select'   => 'T',
//  'select|CA'   => 'M', // Multiple Selection only under EDIT (C) and Add (A)
  'select|CA'   => 'C', // Multiple Selection only under EDIT (C) and Add (A)  
  'maxlen'   => 100,
  'sort'     => true
);
$opts['fdd']['assign_to_notify_only']['textarea']['rows'] = 4;
$opts['fdd']['assign_to_notify_only']['textarea']['cols'] = 25;

//added by jon (ver1.19b)
$table_column_name="assign_to_notify_only";
include "jon/jon_query_values2_multiselect.php";

$opts['fdd']['last_edited_by'] = array(
  'name'     => 'Τελευταία <BR>αλλαγή<BR>από', //
  'select'   => 'D',
  'maxlen'   => 8,
  'sort'     => true
);
$opts['fdd']['last_edited_by']['values2'] = array($login => $login);

$opts['fdd']['id'] = array(
  'name'     => 'ID',
  'select'   => 'T',
  'options'  => 'AVCPDR', // auto increment
  'maxlen'   => 11,
  'default'  => '0',
  'sort'     => true
);
include_once "main_menu_view_only.php";  //BEFORE new phpMyEdit Class
// Now important call to phpMyEdit
require_once 'extensions/phpMyEdit-mce-cal.class.php';
new phpMyEdit_mce_cal($opts);

?>
<script type="text/javascript">
  Calendar.setup(
    {
      inputField  : "PME_data_Date_Reg",
      ifFormat    : "%Y-%m-%d",
	  showsTime   : false,
      singleClick : true,
	  label       => "ΗΜΕΡΟΛΟΓΙΟ",
	  button      : "PME_data_Date_Reg"

    }
  );
</script>

</body>
</html>